# Generated by Django 5.2.1 on 2025-05-14 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_aula', models.CharField(max_length=10, unique=True)),
                ('numero_aula', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_estudiante', models.CharField(max_length=10, unique=True)),
                ('identificacion', models.CharField(max_length=20)),
                ('primer_nombre', models.CharField(max_length=100)),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('grado', models.CharField(max_length=50)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='apphorarios.aula')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_profesor', models.CharField(max_length=10, unique=True)),
                ('identificacion', models.CharField(max_length=20)),
                ('primer_nombre', models.CharField(max_length=100)),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('materia_dicta', models.CharField(max_length=100)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesores', to='apphorarios.aula')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_clase', models.CharField(max_length=255)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='apphorarios.aula')),
                ('estudiantes', models.ManyToManyField(related_name='clases', to='apphorarios.estudiante')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='apphorarios.profesor')),
            ],
        ),
    ]
