# Generated by Django 5.2.8 on 2026-06-12 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphorarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='abreviatura',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='color',
            field=models.CharField(default='#FFFFFF', help_text='Color en formato HEX (ej. #FF5733)', max_length=7),
        ),
        migrations.AddField(
            model_name='grado',
            name='aula_base',
            field=models.ForeignKey(blank=True, help_text='Aula principal para este grado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grados_base', to='apphorarios.aula'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='abreviatura',
            field=models.CharField(blank=True, default='', help_text='Ej. JP para Juan Pérez', max_length=10),
        ),
        migrations.CreateModel(
            name='DisponibilidadProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LU', 'Lunes'), ('MA', 'Martes'), ('MI', 'Miércoles'), ('JU', 'Jueves'), ('VI', 'Viernes')], max_length=2)),
                ('disponible', models.BooleanField(default=True)),
                ('hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apphorarios.hora')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='apphorarios.profesor')),
            ],
            options={
                'unique_together': {('profesor', 'dia', 'hora')},
            },
        ),
    ]
