# Generated by Django 5.2.1 on 2025-05-22 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphorarios', '0002_alter_clase_descripcion_clase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_asignatura', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(default='Sin nombre', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_grado', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(default='Sin grado', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='08:00 - 09:00', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='materia_dicta',
        ),
        migrations.AlterField(
            model_name='aula',
            name='numero_aula',
            field=models.CharField(default='Aula 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='aula',
            name='ubicacion',
            field=models.CharField(default='Ubicación desconocida', max_length=100),
        ),
        migrations.AlterField(
            model_name='clase',
            name='descripcion_clase',
            field=models.CharField(default='Clase sin descripción', max_length=100),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='primer_apellido',
            field=models.CharField(default='Apellido', max_length=100),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='primer_nombre',
            field=models.CharField(default='Nombre', max_length=100),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='primer_apellido',
            field=models.CharField(default='Apellido', max_length=100),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='primer_nombre',
            field=models.CharField(default='Nombre', max_length=100),
        ),
        migrations.AddField(
            model_name='profesor',
            name='asignatura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profesores', to='apphorarios.asignatura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='grado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesores', to='apphorarios.grado'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='apphorarios.grado'),
        ),
        migrations.AddField(
            model_name='clase',
            name='hora',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='apphorarios.hora'),
            preserve_default=False,
        ),
    ]
