# Generated by Django 5.2.8 on 2026-06-12 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphorarios', '0002_asignatura_abreviatura_asignatura_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_ficha', models.CharField(default='Ficha sin descripción', max_length=100)),
                ('horas_totales', models.IntegerField(default=1, help_text='Cantidad de horas a la semana')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='apphorarios.asignatura')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='apphorarios.grado')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='apphorarios.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='FichaAsignada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LU', 'Lunes'), ('MA', 'Martes'), ('MI', 'Miércoles'), ('JU', 'Jueves'), ('VI', 'Viernes')], default='LU', max_length=2)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_asignadas', to='apphorarios.aula')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='apphorarios.ficha')),
                ('hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_asignadas', to='apphorarios.hora')),
            ],
            options={
                'unique_together': {('aula', 'hora', 'dia')},
            },
        ),
        migrations.DeleteModel(
            name='Clase',
        ),
    ]
