# Generated by Django 5.2.1 on 2025-06-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphorarios', '0003_estudiante_usuario_profesor_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grado',
            name='nombre',
            field=models.CharField(choices=[('Preescolar', 'Preescolar'), ('Primaria', 'Primaria'), ('Secundaria', 'Secundaria')], default='Primaria', max_length=100),
        ),
    ]
