# Generated by Django 5.2.1 on 2025-06-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphorarios', '0003_asignatura_grado_hora_remove_profesor_materia_dicta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='capacidad',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='aula',
            name='nombre',
            field=models.CharField(default='Aula', max_length=100),
        ),
        migrations.AddField(
            model_name='hora',
            name='hora_fin',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='hora',
            name='hora_inicio',
            field=models.TimeField(default='08:00'),
        ),
    ]
