# Generated by Django 5.2.8 on 2026-06-06 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphorarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='intensidad_horaria',
            field=models.PositiveIntegerField(default=0, help_text='Horas semanales asignadas'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='codigo_estudiante',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='codigo_profesor',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ExcepcionHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LU', 'Lunes'), ('MA', 'Martes'), ('MI', 'Miércoles'), ('JU', 'Jueves'), ('VI', 'Viernes'), ('SA', 'Sábado'), ('DO', 'Domingo')], max_length=2)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excepciones', to='apphorarios.profesor')),
            ],
            options={
                'ordering': ['profesor', 'dia', 'hora_inicio'],
                'unique_together': {('profesor', 'dia', 'hora_inicio', 'hora_fin')},
            },
        ),
    ]
