# Generated by Django 5.2.8 on 2026-06-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphorarios', '0002_profesor_intensidad_horaria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistribucionHoraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('2-2', '2 bloques de 2 horas'), ('2-1-1', '1 bloque de 2 + 2 bloques de 1 hora'), ('1-1-1-1', '4 bloques de 1 hora'), ('3-1', '1 bloque de 3 + 1 bloque de 1 hora'), ('1-1-1', '3 bloques de 1 hora'), ('2-1', '1 bloque de 2 + 1 bloque de 1 hora'), ('CUSTOM', 'Personalizado')], max_length=10)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de cómo se reparten las horas.')),
            ],
            options={
                'verbose_name': 'Distribución horaria',
                'verbose_name_plural': 'Distribuciones horarias',
            },
        ),
        migrations.AddField(
            model_name='aula',
            name='grados_permitidos',
            field=models.ManyToManyField(blank=True, help_text='Grados que pueden recibir clase en esta aula. Dejar vacío para permitir todos.', related_name='aulas_permitidas', to='apphorarios.grado'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='aulas',
            field=models.ManyToManyField(blank=True, help_text='Aulas en las que este profesor puede dictar clase.', related_name='profesores_asignados', to='apphorarios.aula'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='codigo_estudiante',
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='identificacion',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='codigo_profesor',
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='identificacion',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
