# Generated by Django 5.2.8 on 2026-06-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphorarios', '0003_distribucionhoraria_aula_grados_permitidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='codigo_estudiante',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='codigo_profesor',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
