# Generated by Django 5.2.8 on 2026-06-12 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphorarios', '0004_alter_estudiante_codigo_estudiante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LU', 'Lunes'), ('MA', 'Martes'), ('MI', 'Miércoles'), ('JU', 'Jueves'), ('VI', 'Viernes')], max_length=2)),
                ('disponible', models.BooleanField(default=True)),
                ('hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apphorarios.hora')),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_ficha', models.CharField(default='Ficha sin descripción', max_length=100)),
                ('horas_totales', models.IntegerField(default=1, help_text='Cantidad de horas a la semana')),
            ],
        ),
        migrations.CreateModel(
            name='FichaAsignada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LU', 'Lunes'), ('MA', 'Martes'), ('MI', 'Miércoles'), ('JU', 'Jueves'), ('VI', 'Viernes')], default='LU', max_length=2)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='clase',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='clase',
            name='aula',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='grado',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='profesor',
        ),
        migrations.DeleteModel(
            name='DistribucionHoraria',
        ),
        migrations.AlterUniqueTogether(
            name='excepcionhorario',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='excepcionhorario',
            name='profesor',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='grados_permitidos',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='aulas',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='intensidad_horaria',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='abreviatura',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='color',
            field=models.CharField(default='#FFFFFF', help_text='Color en formato HEX (ej. #FF5733)', max_length=7),
        ),
        migrations.AddField(
            model_name='grado',
            name='aula_base',
            field=models.ForeignKey(blank=True, help_text='Aula principal para este grado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grados_base', to='apphorarios.aula'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='abreviatura',
            field=models.CharField(blank=True, default='', help_text='Ej. JP para Juan Pérez', max_length=10),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='codigo_estudiante',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='identificacion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='codigo_profesor',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='identificacion',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='disponibilidadprofesor',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='apphorarios.profesor'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='apphorarios.asignatura'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='apphorarios.grado'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='apphorarios.profesor'),
        ),
        migrations.AddField(
            model_name='fichaasignada',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_asignadas', to='apphorarios.aula'),
        ),
        migrations.AddField(
            model_name='fichaasignada',
            name='ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='apphorarios.ficha'),
        ),
        migrations.AddField(
            model_name='fichaasignada',
            name='hora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_asignadas', to='apphorarios.hora'),
        ),
        migrations.DeleteModel(
            name='Clase',
        ),
        migrations.DeleteModel(
            name='ExcepcionHorario',
        ),
        migrations.AlterUniqueTogether(
            name='disponibilidadprofesor',
            unique_together={('profesor', 'dia', 'hora')},
        ),
        migrations.AlterUniqueTogether(
            name='fichaasignada',
            unique_together={('aula', 'hora', 'dia')},
        ),
    ]
