# Generated by Django 5.2.8 on 2026-06-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphorarios', '0005_disponibilidadprofesor_ficha_fichaasignada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='asignatura',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='grados',
        ),
        migrations.AddField(
            model_name='aula',
            name='abreviatura',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='profesor',
            name='asignaturas',
            field=models.ManyToManyField(blank=True, related_name='profesores', to='apphorarios.asignatura'),
        ),
    ]
