# Generated by Django 5.2.8 on 2026-06-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphorarios', '0006_remove_profesor_asignatura_remove_profesor_grados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='abreviatura',
            field=models.CharField(blank=True, default='', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='aula',
            name='abreviatura',
            field=models.CharField(blank=True, default='', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='aula',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='identificacion',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='grado',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='identificacion',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
