# Generated by Django 5.2.8 on 2026-06-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphorarios', '0007_alter_asignatura_abreviatura_alter_asignatura_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionColegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Institución Educativa Demo', max_length=200)),
                ('anio_lectivo', models.CharField(default='2026', max_length=20)),
                ('periodo', models.CharField(default='Semestre 1', max_length=50)),
            ],
        ),
    ]
