# Generated by Django 5.2.8 on 2026-06-17 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphorarios', '0008_configuracioncolegio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='capacidad',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='horas_totales',
            field=models.IntegerField(default=1, help_text='Cantidad de horas a la semana', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
